export enum NotificationType {
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  BADGE_EARNED = 'BADGE_EARNED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  CONTRACT_UPDATED = 'CONTRACT_UPDATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED'
} 